import type { CatalogRaceRecord } from "@/lib/catalog/types";

/** Iconic epics & mixed-surface bucket-list races (non-UWS / non-global_trail group). */
export const EPIC_LEGACY_RECORDS: CatalogRaceRecord[] = [
  {
    id: "disc-mds",
    name: "Marathon des Sables",
    location: "Sahara, Morocco",
    city: "Ouarzazate",
    country: "Morocco",
    latitude: 30.9333,
    longitude: -6.9,
    event_type: "stage",
    distance_km: 250,
    surface: "trail",
    group: "epic_endurance",
    multi_day: true,
    typical_months: [4],
    edition_date_quality: "month_typical",
    elevation_m_est: 2000,
    tags: ["desert", "heat", "self_supported"],
    aliases: ["marathon des sables", "mds", "marathon of the sands", "sahara mds"],
    match_boost: 0.08,
    region: "africa",
    source: "legacy_epic",
    match_tier: "flagship"
  },
  {
    id: "disc-wser",
    name: "Western States 100",
    location: "Olympic Valley, USA",
    city: "Olympic Valley",
    region_state: "California",
    country: "United States",
    latitude: 39.1964,
    longitude: -120.2358,
    event_type: "ultra",
    distance_km: 161,
    surface: "trail",
    group: "epic_endurance",
    typical_months: [6, 7],
    edition_date_anchor_ymd: "2025-06-28",
    edition_date_window_days: 10,
    edition_date_quality: "anchor",
    elevation_m_est: 5500,
    tags: ["sierra", "historic", "heat"],
    aliases: [
      "western states",
      "western states 100",
      "western states endurance run",
      "ws100",
      "ws 100",
      "squaw valley western states"
    ],
    match_boost: 0.1,
    region: "north_america",
    source: "legacy_epic",
    match_tier: "flagship"
  },
  {
    id: "disc-hardrock",
    name: "Hardrock 100",
    location: "Silverton, USA",
    city: "Silverton",
    region_state: "Colorado",
    country: "United States",
    latitude: 37.8119,
    longitude: -107.6645,
    event_type: "ultra",
    distance_km: 161,
    surface: "trail",
    group: "epic_endurance",
    typical_months: [7],
    edition_date_quality: "month_typical",
    elevation_m_est: 10000,
    tags: ["alpine", "technical", "high_altitude"],
    aliases: ["hardrock", "hardrock 100", "hard rock 100", "hardrock100", "hardrock hundred"],
    match_boost: 0.1,
    region: "north_america",
    source: "legacy_epic",
    match_tier: "flagship"
  },
  {
    id: "disc-leadville",
    name: "Leadville Trail 100",
    location: "Leadville, USA",
    city: "Leadville",
    region_state: "Colorado",
    country: "United States",
    latitude: 39.2508,
    longitude: -106.2925,
    event_type: "ultra",
    distance_km: 161,
    surface: "trail",
    group: "epic_endurance",
    typical_months: [8],
    edition_date_quality: "month_typical",
    elevation_m_est: 4700,
    tags: ["high_altitude", "runnable"],
    aliases: ["leadville", "leadville 100", "lt100", "leadville trail 100", "leadville trail"],
    match_boost: 0.07,
    region: "north_america",
    source: "legacy_epic",
    match_tier: "major"
  },
  {
    id: "disc-badwater",
    name: "Badwater 135",
    location: "Death Valley → Mt Whitney, USA",
    distance_km: 217,
    surface: "road",
    group: "epic_endurance",
    typical_months: [7],
    elevation_m_est: 4500,
    tags: ["heat", "desert", "road_ultra"],
    aliases: ["badwater", "badwater 135"],
    match_boost: 0.08,
    region: "north_america",
    source: "legacy_epic"
  },
  {
    id: "disc-spartathlon",
    name: "Spartathlon",
    location: "Athens → Sparta, Greece",
    distance_km: 246,
    surface: "road",
    group: "epic_endurance",
    multi_day: true,
    typical_months: [9, 10],
    elevation_m_est: 2500,
    tags: ["road", "heat", "historic"],
    aliases: ["spartathlon", "athens to sparta"],
    match_boost: 0.07,
    region: "europe",
    source: "legacy_epic"
  },
  {
    id: "disc-tor",
    name: "Tor des Géants",
    location: "Aosta Valley, Italy",
    distance_km: 330,
    surface: "trail",
    group: "epic_endurance",
    multi_day: true,
    typical_months: [9],
    elevation_m_est: 24000,
    tags: ["alpine", "technical", "stage_race"],
    aliases: ["tor des géants", "tor des geants", "tdg"],
    match_boost: 0.1,
    region: "europe",
    source: "legacy_epic"
  },
  {
    id: "disc-moab",
    name: "Moab 240",
    location: "Moab, USA",
    distance_km: 386,
    surface: "trail",
    group: "epic_endurance",
    multi_day: true,
    typical_months: [10],
    elevation_m_est: 9000,
    tags: ["desert", "technical", "expedition"],
    aliases: ["moab 240", "moab"],
    match_boost: 0.07,
    region: "north_america",
    source: "legacy_epic"
  },
  {
    id: "disc-diagonale",
    name: "La Diagonale des Fous",
    location: "Réunion Island",
    distance_km: 165,
    surface: "trail",
    group: "epic_endurance",
    typical_months: [10],
    elevation_m_est: 10000,
    tags: ["volcanic", "technical", "vert"],
    aliases: ["diagonale", "grand raid", "réunion", "reunion", "diagonale des fous"],
    match_boost: 0.08,
    region: "africa",
    source: "legacy_epic"
  },
  {
    id: "disc-pikes",
    name: "Pikes Peak Marathon",
    location: "Colorado, USA",
    distance_km: 42.2,
    surface: "mixed",
    group: "epic_endurance",
    typical_months: [8, 9],
    elevation_m_est: 2200,
    tags: ["high_altitude", "technical"],
    aliases: ["pikes peak", "pikes peak marathon"],
    match_boost: 0.05,
    region: "north_america",
    source: "legacy_epic"
  },
  {
    id: "disc-two-oceans",
    name: "Two Oceans Marathon",
    location: "Cape Town, South Africa",
    city: "Cape Town",
    region_state: "Western Cape",
    country: "South Africa",
    latitude: -33.9249,
    longitude: 18.4241,
    event_type: "road",
    distance_km: 56,
    surface: "road",
    group: "epic_endurance",
    typical_months: [4],
    edition_date_quality: "month_typical",
    elevation_m_est: 800,
    tags: ["coastal", "ultra_road"],
    aliases: ["two oceans", "two oceans marathon", "two oceans ultra", "tot ultra"],
    match_boost: 0.04,
    region: "africa",
    source: "legacy_epic",
    match_tier: "major"
  }
];
