import type { CatalogRaceRecord } from "@/lib/catalog/types";

/**
 * Recurring global trail ultras (~50 km+) outside the UTMB World Series module.
 * Add rows here or new files + merge in `buildMergedCatalog` — keeps the system scalable.
 */
export const GLOBAL_TRAIL_ULTRA_RECORDS: CatalogRaceRecord[] = [
  {
    id: "disc-gt-transgrancanaria",
    name: "Transgrancanaria",
    location: "Maspalomas, Gran Canaria, Spain",
    city: "Maspalomas",
    region_state: "Canary Islands",
    country: "Spain",
    latitude: 27.7606,
    longitude: -15.586,
    event_type: "ultra",
    distance_km: 126,
    distance_variants_km: [126, 84, 42],
    surface: "trail",
    group: "global_trail",
    event_group: "Major European ultra",
    typical_months: [3],
    edition_date_quality: "month_typical",
    elevation_m_est: 7500,
    tags: ["volcanic", "technical", "heat"],
    aliases: ["transgrancanaria", "transgrancanaria marathon", "tgc", "gran canaria ultra", "tgc ultra"],
    match_boost: 0.06,
    region: "europe",
    source: "global_trail",
    match_tier: "major"
  },
  {
    id: "disc-gt-comrades",
    name: "Comrades Marathon",
    location: "Pietermaritzburg ↔ Durban, South Africa",
    city: "Durban",
    region_state: "KwaZulu-Natal",
    country: "South Africa",
    latitude: -29.8587,
    longitude: 31.0218,
    event_type: "ultra",
    distance_km: 89,
    surface: "road",
    group: "global_trail",
    event_group: "World Majors Trail",
    typical_months: [6],
    edition_date_anchor_ymd: "2025-06-08",
    edition_date_window_days: 14,
    edition_date_quality: "anchor",
    elevation_m_est: 2200,
    tags: ["road_to_trail", "historic", "south_africa"],
    aliases: ["comrades", "comrades marathon", "the comrades", "comrades ultra"],
    match_boost: 0.08,
    region: "africa",
    source: "global_trail",
    match_tier: "flagship"
  },
  {
    id: "disc-gt-zugspitz",
    name: "Zugspitz Ultratrail",
    location: "Garmisch-Partenkirchen, Germany",
    distance_km: 100,
    surface: "trail",
    group: "global_trail",
    typical_months: [6],
    elevation_m_est: 5500,
    tags: ["alpine", "technical"],
    aliases: ["zugspitz", "zugspitz ultra", "zugspitz ultratrail"],
    match_boost: 0.05,
    region: "europe",
    source: "global_trail"
  },
  {
    id: "disc-gt-templiers",
    name: "Grand Trail des Templiers",
    location: "Millau, France",
    distance_km: 76,
    surface: "trail",
    group: "global_trail",
    typical_months: [10],
    elevation_m_est: 3500,
    tags: ["technical", "limestone"],
    aliases: ["les templiers", "templiers", "grand trail templiers"],
    match_boost: 0.05,
    region: "europe",
    source: "global_trail"
  },
  {
    id: "disc-gt-javelina",
    name: "Javelina Jundred",
    location: "Arizona, USA",
    distance_km: 161,
    surface: "trail",
    group: "global_trail",
    typical_months: [10, 11],
    elevation_m_est: 3500,
    tags: ["desert", "runnable", "loops"],
    aliases: ["javelina", "javelina hundred", "javelina jundred"],
    match_boost: 0.06,
    region: "north_america",
    source: "global_trail"
  },
  {
    id: "disc-gt-bear100",
    name: "Bear 100",
    location: "Utah/Idaho, USA",
    distance_km: 161,
    surface: "trail",
    group: "global_trail",
    typical_months: [9],
    elevation_m_est: 5500,
    tags: ["mountain", "technical", "autumn"],
    aliases: ["bear 100", "bear hundred"],
    match_boost: 0.05,
    region: "north_america",
    source: "global_trail"
  },
  {
    id: "disc-gt-cocodona",
    name: "Cocodona 250",
    location: "Arizona, USA",
    distance_km: 402,
    surface: "trail",
    group: "global_trail",
    multi_day: true,
    typical_months: [4],
    elevation_m_est: 12000,
    tags: ["desert", "expedition", "technical"],
    aliases: ["cocodona", "cocodona 250"],
    match_boost: 0.06,
    region: "north_america",
    source: "global_trail"
  },
  {
    id: "disc-gt-hurt100",
    name: "HURT 100",
    location: "Oahu, Hawaii, USA",
    distance_km: 161,
    surface: "trail",
    group: "global_trail",
    typical_months: [1],
    elevation_m_est: 7500,
    tags: ["tropical", "technical", "roots"],
    aliases: ["hurt 100", "hurt100"],
    match_boost: 0.06,
    region: "north_america",
    source: "global_trail"
  },
  {
    id: "disc-gt-volcanic",
    name: "Volcanic 50 (50 mi)",
    location: "Hawaii, USA",
    distance_km: 80,
    surface: "trail",
    group: "global_trail",
    typical_months: [8],
    elevation_m_est: 4000,
    tags: ["volcanic", "technical"],
    aliases: ["volcanic 50", "volcanic fifty"],
    match_boost: 0.04,
    region: "north_america",
    source: "global_trail"
  },
  {
    id: "disc-gt-hasetsune",
    name: "Hasetsune Cup",
    location: "Tokyo area, Japan",
    distance_km: 71,
    surface: "trail",
    group: "global_trail",
    typical_months: [10],
    elevation_m_est: 4500,
    tags: ["technical", "urban_trail"],
    aliases: ["hasetsune", "hasetsune cup"],
    match_boost: 0.05,
    region: "asia",
    source: "global_trail"
  },
  {
    id: "disc-gt-northburn",
    name: "Northburn 100",
    location: "Central Otago, New Zealand",
    distance_km: 161,
    surface: "trail",
    group: "global_trail",
    typical_months: [3],
    elevation_m_est: 9000,
    tags: ["alpine", "technical", "exposure"],
    aliases: ["northburn", "northburn 100"],
    match_boost: 0.05,
    region: "oceania",
    source: "global_trail"
  },
  {
    id: "disc-gt-ultratrailcapetown",
    name: "Ultra-Trail Cape Town",
    location: "Cape Town, South Africa",
    city: "Cape Town",
    region_state: "Western Cape",
    country: "South Africa",
    latitude: -33.9249,
    longitude: 18.4241,
    event_type: "ultra",
    distance_km: 100,
    distance_variants_km: [100, 65, 35],
    surface: "trail",
    group: "global_trail",
    typical_months: [11],
    edition_date_quality: "month_typical",
    elevation_m_est: 4500,
    tags: ["coastal", "technical", "table_mountain"],
    aliases: [
      "ultra trail cape town",
      "ultra-trail cape town",
      "utct",
      "cape town ultra trail",
      "utmb cape town"
    ],
    match_boost: 0.05,
    region: "africa",
    source: "global_trail",
    match_tier: "major"
  },
  {
    id: "disc-gt-patagonia-run",
    name: "Patagonia Run",
    location: "El Bolsón, Argentina",
    distance_km: 100,
    distance_variants_km: [100, 50],
    surface: "trail",
    group: "global_trail",
    typical_months: [4],
    elevation_m_est: 5000,
    tags: ["mountain", "wind"],
    aliases: ["patagonia run"],
    match_boost: 0.05,
    region: "south_america",
    source: "global_trail"
  },
  {
    id: "disc-gt-brazil135",
    name: "Brazil 135",
    location: "Campos do Jordão, Brazil",
    distance_km: 217,
    surface: "trail",
    group: "global_trail",
    multi_day: true,
    typical_months: [1],
    elevation_m_est: 8000,
    tags: ["mountain", "heat", "road_trail_mix"],
    aliases: ["brazil 135"],
    match_boost: 0.04,
    region: "south_america",
    source: "global_trail"
  }
];
