import type { CatalogRaceRecord } from "@/lib/catalog/types";

/**
 * Second wave: globally common road marathons where city/sponsor disambiguation matters.
 * Curated aliases — no bare city names.
 */
export const INTERNATIONAL_MARATHON_WAVE_RECORDS: CatalogRaceRecord[] = [
  {
    id: "disc-seoul",
    name: "Seoul International Marathon",
    official_name: "Seoul Marathon",
    location: "Seoul, South Korea",
    city: "Seoul",
    country: "South Korea",
    latitude: 37.5665,
    longitude: 126.978,
    event_type: "road",
    organizer_name: "Seoul Athletic Association",
    distance_km: 42.2,
    surface: "road",
    group: "major_marathons",
    typical_months: [3],
    edition_date_quality: "month_typical",
    tags: ["asia", "city_major"],
    aliases: ["seoul marathon", "seoul international marathon", "si marathon seoul"],
    match_boost: 0.035,
    region: "asia",
    source: "road_major",
    match_tier: "major"
  },
  {
    id: "disc-barcelona",
    name: "Barcelona Marathon",
    official_name: "Zurich Marató Barcelona",
    location: "Barcelona, Spain",
    city: "Barcelona",
    region_state: "Catalonia",
    country: "Spain",
    latitude: 41.3851,
    longitude: 2.1734,
    event_type: "road",
    distance_km: 42.2,
    surface: "road",
    group: "major_marathons",
    typical_months: [3],
    edition_date_quality: "month_typical",
    tags: ["europe", "city_major"],
    aliases: ["barcelona marathon", "zurich marato barcelona", "zurich marató barcelona", "marato barcelona"],
    match_boost: 0.035,
    region: "europe",
    source: "road_major",
    match_tier: "major"
  },
  {
    id: "disc-hong-kong",
    name: "Hong Kong Marathon",
    location: "Hong Kong",
    city: "Hong Kong",
    country: "Hong Kong",
    latitude: 22.3193,
    longitude: 114.1694,
    event_type: "road",
    distance_km: 42.2,
    surface: "road",
    group: "major_marathons",
    typical_months: [1, 2],
    edition_date_quality: "month_relaxed",
    tags: ["asia", "city_major"],
    aliases: ["hong kong marathon", "hk marathon", "standard chartered hong kong marathon"],
    match_boost: 0.035,
    region: "asia",
    source: "road_major",
    match_tier: "major"
  },
  {
    id: "disc-toronto",
    name: "Toronto Waterfront Marathon",
    official_name: "TCS Toronto Waterfront Marathon",
    location: "Toronto, Canada",
    city: "Toronto",
    region_state: "Ontario",
    country: "Canada",
    latitude: 43.6532,
    longitude: -79.3832,
    event_type: "road",
    distance_km: 42.2,
    surface: "road",
    group: "major_marathons",
    typical_months: [10],
    edition_date_quality: "month_typical",
    tags: ["north_america", "city_major"],
    aliases: ["toronto marathon", "toronto waterfront marathon", "tcs toronto marathon", "tcs toronto waterfront"],
    match_boost: 0.035,
    region: "north_america",
    source: "road_major",
    match_tier: "major"
  },
  {
    id: "disc-houston",
    name: "Houston Marathon",
    official_name: "Chevron Houston Marathon",
    location: "Houston, USA",
    city: "Houston",
    region_state: "Texas",
    country: "United States",
    latitude: 29.7604,
    longitude: -95.3698,
    event_type: "road",
    distance_km: 42.2,
    surface: "road",
    group: "major_marathons",
    typical_months: [1],
    edition_date_quality: "month_typical",
    tags: ["usa_major", "flat"],
    aliases: ["houston marathon", "chevron houston marathon", "chevron houston"],
    match_boost: 0.03,
    region: "north_america",
    source: "road_major",
    match_tier: "major"
  },
  {
    id: "disc-marine-corps",
    name: "Marine Corps Marathon",
    location: "Arlington, USA",
    city: "Arlington",
    region_state: "Virginia",
    country: "United States",
    latitude: 38.8816,
    longitude: -77.091,
    event_type: "road",
    organizer_name: "Marine Corps Marathon Organization",
    distance_km: 42.2,
    surface: "road",
    group: "major_marathons",
    typical_months: [10],
    edition_date_quality: "month_typical",
    tags: ["usa_major", "washington_dc_area"],
    aliases: [
      "marine corps marathon",
      "mcm marathon",
      "marine corps marathon arlington",
      "mcm arlington"
    ],
    match_boost: 0.035,
    region: "north_america",
    source: "road_major",
    match_tier: "major"
  },
  {
    id: "disc-stockholm",
    name: "Stockholm Marathon",
    official_name: "adidas Stockholm Marathon",
    location: "Stockholm, Sweden",
    city: "Stockholm",
    country: "Sweden",
    latitude: 59.3293,
    longitude: 18.0686,
    event_type: "road",
    distance_km: 42.2,
    surface: "road",
    group: "major_marathons",
    typical_months: [6],
    edition_date_quality: "month_typical",
    tags: ["europe", "scenic"],
    aliases: ["stockholm marathon", "adidas stockholm marathon", "stockholm maraton"],
    match_boost: 0.03,
    region: "europe",
    source: "road_major",
    match_tier: "major"
  },
  {
    id: "disc-copenhagen",
    name: "Copenhagen Marathon",
    location: "Copenhagen, Denmark",
    city: "Copenhagen",
    country: "Denmark",
    latitude: 55.6761,
    longitude: 12.5683,
    event_type: "road",
    distance_km: 42.2,
    surface: "road",
    group: "major_marathons",
    typical_months: [5],
    edition_date_quality: "month_typical",
    tags: ["europe", "flat"],
    aliases: ["copenhagen marathon", "cph marathon", "kobenhavn marathon"],
    match_boost: 0.03,
    region: "europe",
    source: "road_major",
    match_tier: "major"
  },
  {
    id: "disc-prague",
    name: "Prague International Marathon",
    official_name: "Prague Marathon",
    location: "Prague, Czech Republic",
    city: "Praha",
    country: "Czech Republic",
    latitude: 50.0755,
    longitude: 14.4378,
    event_type: "road",
    distance_km: 42.2,
    surface: "road",
    group: "major_marathons",
    typical_months: [5],
    edition_date_quality: "month_typical",
    tags: ["europe", "historic"],
    aliases: ["prague marathon", "prague international marathon", "volkswagen prague marathon", "marathon praha"],
    match_boost: 0.03,
    region: "europe",
    source: "road_major",
    match_tier: "major"
  },
  {
    id: "disc-vienna",
    name: "Vienna City Marathon",
    location: "Vienna, Austria",
    city: "Vienna",
    country: "Austria",
    latitude: 48.2082,
    longitude: 16.3738,
    event_type: "road",
    distance_km: 42.2,
    surface: "road",
    group: "major_marathons",
    typical_months: [4],
    edition_date_quality: "month_typical",
    tags: ["europe", "city_major"],
    aliases: ["vienna marathon", "vienna city marathon", "wiener marathon", "wien marathon"],
    match_boost: 0.03,
    region: "europe",
    source: "road_major",
    match_tier: "major"
  },
  {
    id: "disc-seville",
    name: "Seville Marathon",
    official_name: "Zurich Seville Marathon",
    location: "Seville, Spain",
    city: "Seville",
    region_state: "Andalusia",
    country: "Spain",
    latitude: 37.3891,
    longitude: -5.9845,
    event_type: "road",
    distance_km: 42.2,
    surface: "road",
    group: "major_marathons",
    typical_months: [2],
    edition_date_quality: "month_typical",
    tags: ["europe", "fast"],
    aliases: ["seville marathon", "sevilla marathon", "zurich seville marathon", "maraton sevilla"],
    match_boost: 0.03,
    region: "europe",
    source: "road_major",
    match_tier: "major"
  }
];
