import type { CatalogRaceRecord } from "@/lib/catalog/types";

/** Abbott World Marathon Majors + other iconic road marathons (one curated id per recurring event). */
export const ROAD_MAJOR_RECORDS: CatalogRaceRecord[] = [
  {
    id: "disc-london",
    name: "London Marathon",
    official_name: "TCS London Marathon",
    location: "London, United Kingdom",
    city: "London",
    region_state: "England",
    country: "United Kingdom",
    latitude: 51.5073,
    longitude: -0.1276,
    event_type: "road",
    series_name: "London Marathon",
    canonical_series_slug_hint: "london-marathon",
    distance_km: 42.2,
    surface: "road",
    group: "major_marathons",
    typical_months: [4],
    edition_date_quality: "month_typical",
    tags: ["fast", "city_major"],
    aliases: [
      "london marathon",
      "tcs london marathon",
      "tcs london",
      "the london marathon",
      "vitality london marathon",
      "virgin money london marathon"
    ],
    match_boost: 0.05,
    region: "europe",
    source: "road_major",
    match_tier: "flagship"
  },
  {
    id: "disc-boston",
    name: "Boston Marathon",
    location: "Boston, USA",
    city: "Boston",
    region_state: "Massachusetts",
    country: "United States",
    latitude: 42.3601,
    longitude: -71.0589,
    event_type: "road",
    distance_km: 42.2,
    surface: "road",
    group: "major_marathons",
    typical_months: [4],
    edition_date_anchor_ymd: "2025-04-21",
    edition_date_window_days: 12,
    edition_date_quality: "anchor",
    tags: ["historic", "bq"],
    aliases: ["boston marathon", "boston strong", "bq", "boston 26.2"],
    match_boost: 0.05,
    region: "north_america",
    source: "road_major",
    match_tier: "flagship"
  },
  {
    id: "disc-berlin",
    name: "Berlin Marathon",
    location: "Berlin, Germany",
    city: "Berlin",
    country: "Germany",
    latitude: 52.52,
    longitude: 13.405,
    event_type: "road",
    distance_km: 42.2,
    surface: "road",
    group: "major_marathons",
    typical_months: [9],
    edition_date_quality: "month_typical",
    tags: ["fast", "flat"],
    aliases: ["berlin marathon", "bmw berlin marathon"],
    match_boost: 0.05,
    region: "europe",
    source: "road_major",
    match_tier: "flagship"
  },
  {
    id: "disc-chicago",
    name: "Chicago Marathon",
    location: "Chicago, USA",
    city: "Chicago",
    region_state: "Illinois",
    country: "United States",
    latitude: 41.8781,
    longitude: -87.6298,
    event_type: "road",
    distance_km: 42.2,
    surface: "road",
    group: "major_marathons",
    typical_months: [10],
    edition_date_quality: "month_typical",
    tags: ["flat", "city_major"],
    aliases: ["chicago marathon", "bank of america chicago marathon", "bank of america chicago", "chicago 26.2"],
    match_boost: 0.05,
    region: "north_america",
    source: "road_major",
    match_tier: "flagship"
  },
  {
    id: "disc-nyc",
    name: "New York City Marathon",
    location: "New York, USA",
    city: "New York",
    region_state: "New York",
    country: "United States",
    latitude: 40.7128,
    longitude: -74.006,
    event_type: "road",
    distance_km: 42.2,
    surface: "road",
    group: "major_marathons",
    typical_months: [11],
    edition_date_quality: "month_typical",
    tags: ["city_major", "bridges"],
    aliases: [
      "new york city marathon",
      "nyc marathon",
      "new york marathon",
      "tcs new york city marathon",
      "tcs nyc marathon"
    ],
    match_boost: 0.05,
    region: "north_america",
    source: "road_major",
    match_tier: "flagship"
  },
  {
    id: "disc-tokyo",
    name: "Tokyo Marathon",
    location: "Tokyo, Japan",
    city: "Tokyo",
    country: "Japan",
    latitude: 35.6762,
    longitude: 139.6503,
    event_type: "road",
    distance_km: 42.2,
    surface: "road",
    group: "major_marathons",
    typical_months: [3],
    edition_date_quality: "month_typical",
    tags: ["city_major"],
    aliases: ["tokyo marathon", "tokyo 42k"],
    match_boost: 0.05,
    region: "asia",
    source: "road_major",
    match_tier: "flagship"
  },
  {
    id: "disc-valencia",
    name: "Valencia Marathon",
    official_name: "Maratón Valencia",
    location: "Valencia, Spain",
    city: "Valencia",
    region_state: "Valencian Community",
    country: "Spain",
    latitude: 39.4699,
    longitude: -0.3763,
    event_type: "road",
    distance_km: 42.2,
    surface: "road",
    group: "major_marathons",
    typical_months: [12],
    edition_date_quality: "month_typical",
    tags: ["fast", "flat"],
    aliases: ["valencia marathon", "maraton valencia", "maratón valencia", "trinidad alfonso valencia"],
    match_boost: 0.04,
    region: "europe",
    source: "road_major",
    match_tier: "major"
  },
  {
    id: "disc-paris",
    name: "Paris Marathon",
    location: "Paris, France",
    city: "Paris",
    country: "France",
    latitude: 48.8566,
    longitude: 2.3522,
    event_type: "road",
    distance_km: 42.2,
    surface: "road",
    group: "major_marathons",
    typical_months: [4],
    edition_date_quality: "month_typical",
    tags: ["city_major"],
    aliases: ["paris marathon", "schneider electric paris marathon", "marathon de paris"],
    match_boost: 0.04,
    region: "europe",
    source: "road_major",
    match_tier: "major"
  },
  {
    id: "disc-amsterdam",
    name: "Amsterdam Marathon",
    official_name: "TCS Amsterdam Marathon",
    location: "Amsterdam, Netherlands",
    city: "Amsterdam",
    country: "Netherlands",
    latitude: 52.3676,
    longitude: 4.9041,
    event_type: "road",
    distance_km: 42.2,
    surface: "road",
    group: "major_marathons",
    typical_months: [10],
    edition_date_quality: "month_typical",
    tags: ["fast", "flat", "city_major"],
    aliases: ["amsterdam marathon", "tcs amsterdam marathon", "tcs amsterdam"],
    match_boost: 0.04,
    region: "europe",
    source: "road_major",
    match_tier: "major"
  },
  {
    id: "disc-rotterdam",
    name: "Rotterdam Marathon",
    location: "Rotterdam, Netherlands",
    city: "Rotterdam",
    country: "Netherlands",
    latitude: 51.9244,
    longitude: 4.4777,
    event_type: "road",
    distance_km: 42.2,
    surface: "road",
    group: "major_marathons",
    typical_months: [4],
    edition_date_quality: "month_typical",
    tags: ["fast", "flat"],
    aliases: ["rotterdam marathon", "nn marathon rotterdam", "nn rotterdam marathon"],
    match_boost: 0.04,
    region: "europe",
    source: "road_major",
    match_tier: "major"
  },
  {
    id: "disc-sydney",
    name: "Sydney Marathon",
    location: "Sydney, Australia",
    city: "Sydney",
    region_state: "New South Wales",
    country: "Australia",
    latitude: -33.8688,
    longitude: 151.2093,
    event_type: "road",
    distance_km: 42.2,
    surface: "road",
    group: "major_marathons",
    typical_months: [9],
    edition_date_quality: "month_typical",
    tags: ["city_major", "oceania"],
    aliases: ["sydney marathon", "sydney running festival marathon"],
    match_boost: 0.04,
    region: "oceania",
    source: "road_major",
    match_tier: "major"
  },
  {
    id: "disc-los-angeles",
    name: "Los Angeles Marathon",
    location: "Los Angeles, USA",
    city: "Los Angeles",
    region_state: "California",
    country: "United States",
    latitude: 34.0522,
    longitude: -118.2437,
    event_type: "road",
    distance_km: 42.2,
    surface: "road",
    group: "major_marathons",
    typical_months: [3],
    edition_date_quality: "month_typical",
    tags: ["city_major", "usa_major"],
    aliases: ["los angeles marathon", "la marathon", "lam"],
    match_boost: 0.035,
    region: "north_america",
    source: "road_major",
    match_tier: "major"
  },
  {
    id: "disc-rome",
    name: "Rome Marathon",
    official_name: "Run Rome The Marathon",
    location: "Rome, Italy",
    city: "Rome",
    country: "Italy",
    latitude: 41.9028,
    longitude: 12.4964,
    event_type: "road",
    distance_km: 42.2,
    surface: "road",
    group: "major_marathons",
    typical_months: [3],
    edition_date_quality: "month_typical",
    tags: ["historic", "city_major"],
    aliases: ["rome marathon", "maratona di roma", "run rome the marathon"],
    match_boost: 0.035,
    region: "europe",
    source: "road_major",
    match_tier: "major"
  }
];
