import type { CatalogRaceRecord } from "@/lib/catalog/types";

/**
 * High-signal UK road marathons / halves + iconic UK ultras.
 * Curated aliases only — no generic city+marathon tokens alone.
 */
export const UK_MAJOR_RECORDS: CatalogRaceRecord[] = [
  {
    id: "disc-uk-manchester-marathon",
    name: "Manchester Marathon",
    location: "Manchester, United Kingdom",
    city: "Manchester",
    region_state: "England",
    country: "United Kingdom",
    latitude: 53.4808,
    longitude: -2.2426,
    event_type: "road",
    distance_km: 42.2,
    surface: "road",
    group: "major_marathons",
    typical_months: [4],
    edition_date_quality: "month_typical",
    tags: ["uk", "flat", "city_major"],
    aliases: ["manchester marathon", "mcr marathon", "adidas manchester marathon"],
    match_boost: 0.04,
    region: "europe",
    source: "road_major",
    match_tier: "major"
  },
  {
    id: "disc-uk-brighton-marathon",
    name: "Brighton Marathon",
    location: "Brighton, United Kingdom",
    city: "Brighton",
    region_state: "England",
    country: "United Kingdom",
    latitude: 50.8225,
    longitude: -0.1372,
    event_type: "road",
    distance_km: 42.2,
    surface: "road",
    group: "major_marathons",
    typical_months: [4],
    edition_date_quality: "month_typical",
    tags: ["uk", "coastal"],
    aliases: ["brighton marathon", "brighton marathon weekend"],
    match_boost: 0.035,
    region: "europe",
    source: "road_major",
    match_tier: "major"
  },
  {
    id: "disc-uk-edinburgh-marathon",
    name: "Edinburgh Marathon",
    location: "Edinburgh, United Kingdom",
    city: "Edinburgh",
    region_state: "Scotland",
    country: "United Kingdom",
    latitude: 55.9533,
    longitude: -3.1883,
    event_type: "road",
    distance_km: 42.2,
    surface: "road",
    group: "major_marathons",
    typical_months: [5],
    edition_date_quality: "month_typical",
    tags: ["uk", "scotland"],
    aliases: ["edinburgh marathon", "emf marathon", "edinburgh marathon festival"],
    match_boost: 0.035,
    region: "europe",
    source: "road_major",
    match_tier: "major"
  },
  {
    id: "disc-uk-loch-ness-marathon",
    name: "Loch Ness Marathon",
    location: "Inverness, United Kingdom",
    city: "Inverness",
    region_state: "Scotland",
    country: "United Kingdom",
    latitude: 57.4778,
    longitude: -4.2247,
    event_type: "road",
    distance_km: 42.2,
    surface: "road",
    group: "major_marathons",
    typical_months: [10],
    edition_date_quality: "month_typical",
    tags: ["uk", "scotland", "scenic"],
    aliases: ["loch ness marathon", "ness marathon"],
    match_boost: 0.035,
    region: "europe",
    source: "road_major",
    match_tier: "major"
  },
  {
    id: "disc-uk-great-north-run",
    name: "Great North Run",
    location: "Newcastle upon Tyne, United Kingdom",
    city: "Newcastle upon Tyne",
    region_state: "England",
    country: "United Kingdom",
    latitude: 54.9783,
    longitude: -1.6178,
    event_type: "road",
    distance_km: 21.1,
    surface: "road",
    group: "major_marathons",
    typical_months: [9],
    edition_date_quality: "month_typical",
    tags: ["uk", "half_marathon", "mass_participation"],
    aliases: ["great north run", "gnr", "great north run half"],
    match_boost: 0.04,
    region: "europe",
    source: "road_major",
    match_tier: "major"
  },
  {
    id: "disc-uk-lakeland-100",
    name: "Lakeland 100",
    location: "Coniston, United Kingdom",
    city: "Coniston",
    region_state: "England",
    country: "United Kingdom",
    latitude: 54.3683,
    longitude: -3.0731,
    event_type: "ultra",
    distance_km: 161,
    surface: "trail",
    group: "global_trail",
    typical_months: [7],
    edition_date_quality: "month_typical",
    elevation_m_est: 6000,
    tags: ["uk", "lake_district", "technical"],
    aliases: ["lakeland 100", "lakeland 100 ultra", "lakeland trail 100"],
    match_boost: 0.05,
    region: "europe",
    source: "global_trail",
    match_tier: "major"
  },
  {
    id: "disc-uk-snowdonia-uts",
    name: "Ultra-Trail Snowdonia",
    location: "Llanberis, United Kingdom",
    city: "Llanberis",
    region_state: "Wales",
    country: "United Kingdom",
    latitude: 53.1176,
    longitude: -4.1085,
    event_type: "ultra",
    distance_km: 100,
    distance_variants_km: [100, 50],
    surface: "trail",
    group: "global_trail",
    typical_months: [5],
    edition_date_quality: "month_typical",
    elevation_m_est: 6500,
    tags: ["uk", "wales", "mountain"],
    aliases: ["ultra trail snowdonia", "uts snowdonia", "snowdonia ultra", "ultra trail snowdonia by utmb"],
    match_boost: 0.05,
    region: "europe",
    source: "global_trail",
    match_tier: "major"
  }
];
