import type { CatalogRaceRecord } from "@/lib/catalog/types";

const UWS = "UTMB World Series";

/** Chamonix finals week + global UTMB World Series events (recurring editions, one id per race). */
export const UTMB_WORLD_SERIES_RECORDS: CatalogRaceRecord[] = [
  {
    id: "disc-utmb",
    name: "UTMB",
    location: "Chamonix, France",
    distance_km: 171,
    surface: "trail",
    group: "utmb",
    event_group: UWS,
    typical_months: [8, 9],
    elevation_m_est: 10000,
    tags: ["alpine", "technical", "utmb_finals", "bucket_list"],
    aliases: ["utmb", "ultra trail du mont blanc", "ultra-trail du mont-blanc", "mont blanc utmb"],
    match_boost: 0.12,
    region: "europe",
    source: "utmb_ws"
  },
  {
    id: "disc-ccc",
    name: "CCC",
    location: "Courmayeur → Chamonix",
    distance_km: 101,
    surface: "trail",
    group: "utmb",
    event_group: UWS,
    typical_months: [8, 9],
    elevation_m_est: 6100,
    tags: ["alpine", "technical", "utmb_finals"],
    aliases: ["ccc", "utmb ccc", "courmayeur chamonix ccc", "100k utmb"],
    match_boost: 0.1,
    region: "europe",
    source: "utmb_ws"
  },
  {
    id: "disc-occ",
    name: "OCC",
    location: "Orsières → Chamonix",
    distance_km: 55,
    surface: "trail",
    group: "utmb",
    event_group: UWS,
    typical_months: [8, 9],
    elevation_m_est: 3500,
    tags: ["alpine", "technical", "runnable", "utmb_finals"],
    aliases: ["occ", "orsieres", "orcières occ"],
    match_boost: 0.09,
    region: "europe",
    source: "utmb_ws"
  },
  {
    id: "disc-tds",
    name: "TDS",
    location: "Courmayeur → Chamonix",
    distance_km: 145,
    surface: "trail",
    group: "utmb",
    event_group: UWS,
    typical_months: [8, 9],
    elevation_m_est: 9100,
    tags: ["alpine", "technical", "utmb_finals"],
    aliases: ["tds", "sur les traces", "ducs de savoie", "traces des ducs"],
    match_boost: 0.1,
    region: "europe",
    source: "utmb_ws"
  },
  {
    id: "disc-etr",
    name: "ETR",
    location: "Orsières → Martigny",
    distance_km: 55,
    surface: "trail",
    group: "utmb",
    event_group: UWS,
    typical_months: [8, 9],
    elevation_m_est: 3200,
    tags: ["mountain", "technical"],
    aliases: ["etr", "trail des géants", "trail des geants"],
    match_boost: 0.08,
    region: "europe",
    source: "utmb_ws"
  },
  {
    id: "disc-lavaredo",
    name: "Ultra Trail Cortina",
    location: "Cortina d'Ampezzo, Italy",
    distance_km: 120,
    surface: "trail",
    group: "utmb",
    event_group: UWS,
    typical_months: [6, 7],
    elevation_m_est: 5800,
    tags: ["alpine", "technical", "dolomites"],
    aliases: ["lavaredo", "ultra trail cortina", "cortina trail", "utmb lavaredo"],
    match_boost: 0.08,
    region: "europe",
    source: "utmb_ws"
  },
  {
    id: "disc-uws-penyagolosa",
    name: "MiM / CSP (Penyagolosa Trails)",
    location: "Castellón, Spain",
    distance_km: 60,
    distance_variants_km: [100, 60],
    surface: "trail",
    group: "utmb",
    event_group: UWS,
    typical_months: [4],
    elevation_m_est: 3500,
    tags: ["mountain", "mediterranean"],
    aliases: ["penyagolosa", "mim csp", "csp mim"],
    match_boost: 0.06,
    region: "europe",
    source: "utmb_ws"
  },
  {
    id: "disc-uws-valdaran",
    name: "Val d'Aran by UTMB",
    location: "Vielha, Spain",
    distance_km: 105,
    distance_variants_km: [162, 105, 55],
    surface: "trail",
    group: "utmb",
    event_group: UWS,
    typical_months: [7],
    elevation_m_est: 6500,
    tags: ["pyrenees", "alpine"],
    aliases: ["val d aran", "val d'aran utmb", "aran by utmb"],
    match_boost: 0.07,
    region: "europe",
    source: "utmb_ws"
  },
  {
    id: "disc-uws-miut",
    name: "MIUT (Madeira Island Ultra Trail)",
    location: "Madeira, Portugal",
    distance_km: 115,
    distance_variants_km: [115, 85, 42],
    surface: "trail",
    group: "utmb",
    event_group: UWS,
    typical_months: [4],
    elevation_m_est: 7200,
    tags: ["island", "technical", "vert"],
    aliases: ["miut", "madeira ultra"],
    match_boost: 0.07,
    region: "europe",
    source: "utmb_ws"
  },
  {
    id: "disc-uws-eiger",
    name: "Eiger Ultra Trail",
    location: "Grindelwald, Switzerland",
    distance_km: 101,
    distance_variants_km: [101, 51, 35],
    surface: "trail",
    group: "utmb",
    event_group: UWS,
    typical_months: [7],
    elevation_m_est: 6700,
    tags: ["alpine", "technical"],
    aliases: ["eiger ultra", "eiger trail"],
    match_boost: 0.07,
    region: "europe",
    source: "utmb_ws"
  },
  {
    id: "disc-uws-swisspeaks",
    name: "Swiss Peaks Trail",
    location: "Goms, Switzerland",
    distance_km: 170,
    distance_variants_km: [170, 90, 42],
    surface: "trail",
    group: "utmb",
    event_group: UWS,
    typical_months: [9],
    elevation_m_est: 11000,
    tags: ["alpine", "technical", "high_passes"],
    aliases: ["swiss peaks"],
    match_boost: 0.07,
    region: "europe",
    source: "utmb_ws"
  },
  {
    id: "disc-uws-mozart",
    name: "Mozart 100",
    location: "Salzburg, Austria",
    distance_km: 105,
    surface: "trail",
    group: "utmb",
    event_group: UWS,
    typical_months: [6],
    elevation_m_est: 5500,
    tags: ["alpine", "runnable"],
    aliases: ["mozart 100", "mozart ultra"],
    match_boost: 0.06,
    region: "europe",
    source: "utmb_ws"
  },
  {
    id: "disc-uws-istria",
    name: "100 Miles of Istria",
    location: "Istria, Croatia",
    distance_km: 171,
    distance_variants_km: [171, 110, 69],
    surface: "trail",
    group: "utmb",
    event_group: UWS,
    typical_months: [4],
    elevation_m_est: 6000,
    tags: ["coastal", "technical", "karst"],
    aliases: ["istria 100", "100 miles istria"],
    match_boost: 0.06,
    region: "europe",
    source: "utmb_ws"
  },
  {
    id: "disc-uws-tarawera",
    name: "Tarawera Ultramarathon",
    location: "Rotorua, New Zealand",
    distance_km: 102,
    distance_variants_km: [102, 87, 50],
    surface: "trail",
    group: "utmb",
    event_group: UWS,
    typical_months: [2],
    elevation_m_est: 3200,
    tags: ["forest", "runnable", "volcanic"],
    aliases: ["tarawera", "tarawera ultra"],
    match_boost: 0.07,
    region: "oceania",
    source: "utmb_ws"
  },
  {
    id: "disc-uws-uta",
    name: "Ultra-Trail Australia (UTA)",
    location: "Blue Mountains, Australia",
    distance_km: 100,
    distance_variants_km: [100, 50, 22],
    surface: "trail",
    group: "utmb",
    event_group: UWS,
    typical_months: [5],
    elevation_m_est: 4400,
    tags: ["technical", "stairs", "blue_mountains"],
    aliases: ["uta100", "ultra trail australia", "north face 100"],
    match_boost: 0.07,
    region: "oceania",
    source: "utmb_ws"
  },
  {
    id: "disc-uws-hk100",
    name: "Hong Kong 100",
    location: "Hong Kong SAR",
    distance_km: 103,
    surface: "trail",
    group: "utmb",
    event_group: UWS,
    typical_months: [1, 2],
    elevation_m_est: 5000,
    tags: ["technical", "humid", "stairs"],
    aliases: ["hk100", "hong kong 100", "vibram hk"],
    match_boost: 0.08,
    region: "asia",
    source: "utmb_ws"
  },
  {
    id: "disc-uws-chiangmai",
    name: "Chiang Mai Thailand by UTMB",
    location: "Chiang Mai, Thailand",
    distance_km: 100,
    distance_variants_km: [100, 50, 25],
    surface: "trail",
    group: "utmb",
    event_group: UWS,
    typical_months: [12],
    elevation_m_est: 4500,
    tags: ["tropical", "technical"],
    aliases: ["chiang mai utmb", "thailand by utmb"],
    match_boost: 0.06,
    region: "asia",
    source: "utmb_ws"
  },
  {
    id: "disc-uws-gaoligong",
    name: "Gaoligong by UTMB",
    location: "Yunnan, China",
    distance_km: 168,
    distance_variants_km: [168, 100, 55],
    surface: "trail",
    group: "utmb",
    event_group: UWS,
    typical_months: [3],
    elevation_m_est: 9000,
    tags: ["mountain", "technical", "himalayan_foothills"],
    aliases: ["gaoligong", "gaoligong utmb"],
    match_boost: 0.06,
    region: "asia",
    source: "utmb_ws"
  },
  {
    id: "disc-uws-wumeng",
    name: "Wumeng Mountain 100 by UTMB",
    location: "Guizhou, China",
    distance_km: 100,
    surface: "trail",
    group: "utmb",
    event_group: UWS,
    typical_months: [4],
    elevation_m_est: 5500,
    tags: ["mountain", "technical"],
    aliases: ["wumeng", "wumeng 100"],
    match_boost: 0.05,
    region: "asia",
    source: "utmb_ws"
  },
  {
    id: "disc-uws-canyons",
    name: "Canyons Endurance Runs by UTMB",
    location: "California, USA",
    distance_km: 100,
    distance_variants_km: [100, 50, 25],
    surface: "trail",
    group: "utmb",
    event_group: UWS,
    typical_months: [4],
    elevation_m_est: 5500,
    tags: ["sierra", "technical", "western_states_qualifier"],
    aliases: ["canyons 100", "canyons utmb", "canyons endurance"],
    match_boost: 0.08,
    region: "north_america",
    source: "utmb_ws"
  },
  {
    id: "disc-uws-blackcanyon",
    name: "Black Canyon Ultras by UTMB",
    location: "Arizona, USA",
    distance_km: 100,
    distance_variants_km: [100, 60],
    surface: "trail",
    group: "utmb",
    event_group: UWS,
    typical_months: [2],
    elevation_m_est: 2400,
    tags: ["desert", "runnable", "western_states_qualifier"],
    aliases: ["black canyon ultra", "black canyon 100"],
    match_boost: 0.07,
    region: "north_america",
    source: "utmb_ws"
  },
  {
    id: "disc-uws-quebec",
    name: "Quebec Mega Trail",
    location: "Quebec, Canada",
    distance_km: 100,
    distance_variants_km: [160, 100, 50],
    surface: "trail",
    group: "utmb",
    event_group: UWS,
    typical_months: [7],
    elevation_m_est: 5000,
    tags: ["technical", "forest"],
    aliases: ["quebec mega trail", "qmt"],
    match_boost: 0.06,
    region: "north_america",
    source: "utmb_ws"
  },
  {
    id: "disc-uws-kings",
    name: "Kings by UTMB",
    location: "California, USA",
    distance_km: 100,
    surface: "trail",
    group: "utmb",
    event_group: UWS,
    typical_months: [11],
    elevation_m_est: 5000,
    tags: ["mountain", "technical"],
    aliases: ["kings utmb"],
    match_boost: 0.05,
    region: "north_america",
    source: "utmb_ws"
  },
  {
    id: "disc-uws-uthc",
    name: "Ultra-Trail Harricana",
    location: "Quebec, Canada",
    distance_km: 125,
    distance_variants_km: [125, 80, 28],
    surface: "trail",
    group: "utmb",
    event_group: UWS,
    typical_months: [9],
    elevation_m_est: 3500,
    tags: ["boreal", "technical"],
    aliases: ["harricana", "uthc"],
    match_boost: 0.05,
    region: "north_america",
    source: "utmb_ws"
  },
  {
    id: "disc-uws-southwest",
    name: "Southwest Traverse by UTMB",
    location: "Texas, USA",
    distance_km: 100,
    surface: "trail",
    group: "utmb",
    event_group: UWS,
    typical_months: [10],
    elevation_m_est: 3500,
    tags: ["desert", "technical"],
    aliases: ["southwest traverse"],
    match_boost: 0.05,
    region: "north_america",
    source: "utmb_ws"
  },
  {
    id: "disc-uws-fuji",
    name: "Fuji by UTMB",
    location: "Mount Fuji, Japan",
    distance_km: 100,
    distance_variants_km: [165, 100, 69],
    surface: "trail",
    group: "utmb",
    event_group: UWS,
    typical_months: [9],
    elevation_m_est: 7000,
    tags: ["volcanic", "technical", "alpine"],
    aliases: ["fuji 100", "fuji utmb", "mt fuji ultra"],
    match_boost: 0.07,
    region: "asia",
    source: "utmb_ws"
  },
  {
    id: "disc-uws-singapore",
    name: "Singapore Eco Trail by UTMB",
    location: "Singapore",
    distance_km: 50,
    distance_variants_km: [100, 50],
    surface: "trail",
    group: "utmb",
    event_group: UWS,
    typical_months: [10],
    elevation_m_est: 2500,
    tags: ["tropical", "technical"],
    aliases: ["singapore eco trail"],
    match_boost: 0.05,
    region: "asia",
    source: "utmb_ws"
  },
  {
    id: "disc-uws-southafrica",
    name: "South Africa by UTMB",
    location: "Western Cape, South Africa",
    distance_km: 100,
    surface: "trail",
    group: "utmb",
    event_group: UWS,
    typical_months: [10],
    elevation_m_est: 4000,
    tags: ["mountain", "fynbos"],
    aliases: ["south africa utmb"],
    match_boost: 0.05,
    region: "africa",
    source: "utmb_ws"
  },
];
